name: Linting
on:
  - push
jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init Packer
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: pre-commit
        uses: pre-commit/action@v2.0.3
